from pathlib import Path

ROOT = Path(__file__).resolve().parent
DOCS = ROOT / "docs"
API = DOCS / "api"
DOCS.mkdir(exist_ok=True)
API.mkdir(exist_ok=True)


def w(rel, text):
    p = ROOT / rel
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(text, encoding="utf-8", newline="\n")
    print("  OK  " + rel)


# ---------------------------------------------------------------
# requirements-docs.txt
# ---------------------------------------------------------------
w(
    "requirements-docs.txt",
    "\n".join(
        [
            "mkdocs>=1.6",
            "mkdocs-material>=9.5",
            "mkdocstrings[python]>=0.26",
            "pymdown-extensions>=10.8",
            "",
        ]
    ),
)


# ---------------------------------------------------------------
# mkdocs.yml
# ---------------------------------------------------------------
w(
    "mkdocs.yml",
    "\n".join(
        [
            "site_name: TELECOM-NET-SIM",
            "site_description: Fully local mobile network simulator (2G-6G) with OSINT/SIGINT analytics",
            "site_url: https://hosras.github.io/MNO-simulator/",
            "repo_url: https://github.com/hosras/MNO-simulator",
            "repo_name: hosras/MNO-simulator",
            "edit_uri: edit/main/docs/",
            "copyright: Copyright &copy; 2026 Hossein Rastegar",
            "",
            "theme:",
            "  name: material",
            "  language: en",
            "  features:",
            "    - navigation.tabs",
            "    - navigation.sections",
            "    - navigation.expand",
            "    - navigation.top",
            "    - navigation.indexes",
            "    - search.suggest",
            "    - search.highlight",
            "    - content.code.copy",
            "    - content.action.edit",
            "    - toc.follow",
            "  palette:",
            '    - media: "(prefers-color-scheme: light)"',
            "      scheme: default",
            "      primary: red",
            "      accent: orange",
            "      toggle:",
            "        icon: material/weather-night",
            "        name: Switch to dark mode",
            '    - media: "(prefers-color-scheme: dark)"',
            "      scheme: slate",
            "      primary: red",
            "      accent: orange",
            "      toggle:",
            "        icon: material/weather-sunny",
            "        name: Switch to light mode",
            "  icon:",
            "    repo: fontawesome/brands/github",
            "",
            "nav:",
            "  - Home: index.md",
            "  - Getting Started: getting-started.md",
            "  - Architecture: architecture.md",
            "  - Testing: testing.md",
            "  - Security: security.md",
            "  - Contributing: contributing.md",
            "  - API Reference:",
            "    - Overview: api/index.md",
            "    - Simulator: api/simulator.md",
            "    - Attack Simulation: api/attack.md",
            "    - Common Utilities: api/common.md",
            "    - Services: api/services.md",
            "",
            "plugins:",
            "  - search",
            "  - mkdocstrings:",
            "      handlers:",
            "        python:",
            "          options:",
            "            docstring_style: google",
            "            show_source: true",
            "            show_root_heading: true",
            "            show_signature_annotations: true",
            "            separate_signature: true",
            "            members_order: source",
            "            merge_init_into_class: true",
            "            show_if_no_docstring: false",
            "",
            "markdown_extensions:",
            "  - admonition",
            "  - attr_list",
            "  - md_in_html",
            "  - tables",
            "  - toc:",
            "      permalink: true",
            "  - pymdownx.highlight",
            "  - pymdownx.inlinehilite",
            "  - pymdownx.superfences",
            "  - pymdownx.tabbed:",
            "      alternate_style: true",
            "  - pymdownx.details",
            "  - pymdownx.tasklist:",
            "      custom_checkbox: true",
            "",
            "extra:",
            "  social:",
            "    - icon: fontawesome/brands/github",
            "      link: https://github.com/hosras/MNO-simulator",
            "  generator: false",
            "",
        ]
    ),
)


# ---------------------------------------------------------------
# docs/index.md
# ---------------------------------------------------------------
w(
    "docs/index.md",
    "\n".join(
        [
            "# TELECOM-NET-SIM",
            "",
            "**Fully local mobile network simulator (2G-6G) with OSINT/SIGINT analytics, attack simulation, and three Streamlit dashboards.**",
            "",
            "[![CI](https://github.com/hosras/MNO-simulator/actions/workflows/ci.yml/badge.svg)](https://github.com/hosras/MNO-simulator/actions/workflows/ci.yml)",
            "[![Coverage](https://raw.githubusercontent.com/hosras/MNO-simulator/main/.github/coverage.svg)](https://github.com/hosras/MNO-simulator)",
            "",
            "---",
            "",
            "## What is it?",
            "",
            "A comprehensive, **offline-only** mobile network simulator that covers:",
            "",
            "- **Simulation**: 2G / 3G / 4G / 5G / 6G topology, subscribers, CDRs, voice bearers, messaging",
            "- **Analysis**: OSINT (public registry, complaints), SIGINT (IMEI churn, SIM-box, impossible-travel)",
            "- **Attack simulator**: 24 attack types across SS7 / Diameter / GTP / PFCP / SIP / O-RAN / 6G",
            "- **Dashboards**: 3 Streamlit apps (operations, analytics, admin)",
            "",
            "## Security Posture",
            "",
            "- **Zero external network calls** (static scan verified)",
            "- Streamlit telemetry **disabled**",
            "- Dashboards bind to **127.0.0.1 only**",
            "- Password hashing with **scrypt** (n=2^14)",
            "- SQLite WAL + online backup API",
            "",
            "## Quick Start",
            "",
            "```bash",
            "python -m venv .venv",
            ".venv/Scripts/activate",
            "pip install -r requirements.txt",
            "",
            "python telecom_net_sim.py",
            "streamlit run telecom_dashboard.py",
            "```",
            "",
            "See [Getting Started](getting-started.md) for full instructions.",
            "",
            "## Quality",
            "",
            "| Metric | Value |",
            "|---|---|",
            "| Tests | **262** |",
            "| Coverage | **98%** |",
            "| Python versions | 3.11 / 3.12 / 3.13 |",
            "| CI | Green |",
            "| Linter | ruff (pre-commit hook) |",
            "",
            "## Where to go next",
            "",
            '<div class="grid cards" markdown>',
            "",
            "- :material-rocket-launch: **[Getting Started](getting-started.md)** -- Install, generate a dataset, and run a dashboard.",
            "- :material-sitemap: **[Architecture](architecture.md)** -- Package layout, shims, and design decisions.",
            "- :material-shield-check: **[Security](security.md)** -- Threat model, local-only guarantees, and evidence.",
            "- :material-test-tube: **[Testing](testing.md)** -- How to run tests, coverage, and CI.",
            "- :material-code-braces: **[API Reference](api/index.md)** -- Autogenerated from source docstrings.",
            "",
            "</div>",
            "",
        ]
    ),
)


# ---------------------------------------------------------------
# docs/getting-started.md
# ---------------------------------------------------------------
w(
    "docs/getting-started.md",
    "\n".join(
        [
            "# Getting Started",
            "",
            "## Prerequisites",
            "",
            "- **Python 3.11+** (tested on 3.11, 3.12, 3.13)",
            "- **~500 MB** free disk space",
            "- **No network access required**",
            "",
            "## Installation",
            "",
            "Windows:",
            "",
            "```cmd",
            "python -m venv .venv",
            ".venv\\Scripts\\activate",
            "pip install -r requirements.txt",
            "```",
            "",
            "Linux / macOS:",
            "",
            "```bash",
            "python3 -m venv .venv",
            "source .venv/bin/activate",
            "pip install -r requirements.txt",
            "```",
            "",
            "For a minimal dev environment, use `requirements-ci.txt` instead.",
            "",
            "## Step 1 - Generate a dataset",
            "",
            "```bash",
            "python telecom_net_sim.py                    # defaults: seed=1403, 5k subs, 60k CDRs",
            "python telecom_net_sim.py --seed 42          # reproducible",
            "python telecom_net_sim.py --random-seed      # non-deterministic",
            "python telecom_net_sim.py --subs 500 --cdrs 2000   # fast smoke run",
            "```",
            "",
            "Outputs to `telecom_sim_output/`:",
            "",
            "- `telecom_sim.db` -- SQLite database",
            "- `report.txt` -- textual summary",
            "- `01..10_*.png` -- 10 charts",
            "",
            "### CLI options",
            "",
            "| Flag | Default | Description |",
            "|---|---|---|",
            "| `--seed` | `1403` | Random seed for reproducibility |",
            "| `--random-seed` | off | Ignore --seed and use a random one |",
            "| `--subs` | `5000` | Number of subscribers |",
            "| `--cdrs` | `60000` | Number of CDR records |",
            "",
            "## Step 2 - (Optional) Run the attack simulator",
            "",
            "```bash",
            "python telecom_attack.py",
            "```",
            "",
            "Or use the **pure core** (no database required):",
            "",
            "```python",
            "from attack_core import generate_scenarios, expand_events",
            "",
            "idx = {",
            '    "cores": {"HSS": ["HSS-01"]},',
            '    "all_cores": [],',
            '    "cells_5g": [],',
            '    "cells_6g": ["6G-001"],',
            "}",
            "scenarios = generate_scenarios(10, idx)   # no DB, no I/O",
            "events    = expand_events(scenarios, samples_per_scenario=20)",
            "```",
            "",
            "## Step 3 - Run a dashboard",
            "",
            "```bash",
            "streamlit run telecom_dashboard.py",
            "streamlit run telecom_radar.py",
            "streamlit run telecom_admin.py",
            "```",
            "",
            "All three bind to `127.0.0.1` only. If a port is busy, pass `--server.port 8502`.",
            "",
            "### First-time admin setup",
            "",
            "The first time you open `telecom_admin.py`, you will be prompted to set a password (min 8 chars). After 5 failed login attempts within 15 minutes, the account is temporarily locked.",
            "",
            "## Troubleshooting",
            "",
            "**Port 8501 is already in use** -- use a different port:",
            "",
            "```bash",
            "streamlit run telecom_dashboard.py --server.port 8502",
            "```",
            "",
            "**pytest fails without a database** -- generate a small one:",
            "",
            "```bash",
            "python telecom_net_sim.py --subs 500 --cdrs 2000",
            "```",
            "",
        ]
    ),
)


# ---------------------------------------------------------------
# docs/architecture.md
# ---------------------------------------------------------------
w(
    "docs/architecture.md",
    "\n".join(
        [
            "# Architecture",
            "",
            "## Package Layout",
            "",
            "The project uses thin **entry-point shims** at the repository root.",
            "The actual implementation lives in three self-contained packages.",
            "",
            "```",
            "MNO-simulator/",
            "- telecom_net_sim.py       # CLI simulator",
            "- telecom_attack.py        # attack orchestrator (DB layer)",
            "- attack_core.py           # pure attack logic (no DB)",
            "- telecom_common.py        # shared utilities + schema",
            "- telecom_ui_common.py     # Streamlit + Plotly helpers",
            "-",
            "- telecom_dashboard.py     # shim -> dashboard.main",
            "- telecom_admin.py         # shim -> admin.main",
            "- telecom_radar.py         # shim -> radar.main",
            "-",
            "- dashboard/               # operations dashboard (13 tabs)",
            "- admin/                   # CRUD + audit + backup (9 tabs)",
            "- radar/                   # statistical analytics (14 tabs)",
            "- tests/                   # pytest suite",
            "- .github/workflows/       # CI",
            "```",
            "",
            "## Why this split?",
            "",
            "### Small diffs",
            "Editing one dashboard tab changes **one small file**, not a 1,300-line monolith.",
            "",
            "### Testable",
            "Services (`anomaly`, `backup`, `pdf`, `period`) have **no Streamlit import**.",
            "They can be unit-tested without a runtime.",
            "",
            "### Backward compatible",
            "`streamlit run telecom_dashboard.py` still works exactly as before.",
            "",
            "## Design Decisions",
            "",
            "### Why local-only?",
            "No network calls anywhere. All data comes from a seeded RNG",
            "(default `SEED = 1403`, overridable via `--seed` / `--random-seed`).",
            "",
            "### Why SQLite?",
            "Single-file DB, zero setup, easy backup/restore, portable.",
            "WAL mode + `sqlite3.Connection.backup()` gives atomic snapshots.",
            "",
            "### Why split attack_core.py from telecom_attack.py?",
            "- **attack_core.py** -- pure functions. No DB, no I/O. 34 unit tests in 0.3 s.",
            "- **telecom_attack.py** -- the DB layer: target indexing, persistence, alert injection, CLI orchestration.",
            "",
            "### Why main() guards everywhere?",
            "Streamlit scripts execute top-to-bottom on every rerun. Without a",
            "guard, `import telecom_dashboard` would run the whole UI.",
            "",
            "## Database Schema",
            "",
            "| Table | Purpose |",
            "|---|---|",
            "| `cells` | 2G-6G cell sites |",
            "| `cores` | Core nodes (MSC, MME, AMF, UPF, NWDAF, ...) |",
            "| `subscribers` | 5,000 subscribers with line classes + encryption |",
            "| `cdrs` | Call detail records |",
            "| `alerts` | Rule-engine alerts |",
            "| `sms_alerts` | SOC SMS dispatch log |",
            "| `audit_log` | Admin actions |",
            "| `attack_scenarios` | Attack simulator output |",
            "| `attack_events` | Attack time-series |",
            "| `sigint_findings` | JSON blobs of SIGINT analysis |",
            "",
        ]
    ),
)


# ---------------------------------------------------------------
# docs/testing.md
# ---------------------------------------------------------------
w(
    "docs/testing.md",
    "\n".join(
        [
            "# Testing",
            "",
            "## Running tests",
            "",
            "```bash",
            "pytest              # fast tests",
            "pytest --run-slow   # also runs the full simulator end-to-end",
            "```",
            "",
            "## Test suite",
            "",
            "**262 tests** across 14 files, executed in under 10 seconds.",
            "",
            "| File | Tests | Focus |",
            "|---|---:|---|",
            "| `test_admin_audit.py` | ~30 | audit log + DB wrappers |",
            "| `test_admin_auth.py` | 13 | session-state helpers |",
            "| `test_admin_backup.py` | 19 | backup / restore |",
            "| `test_admin_rate_limit.py` | 17 | login lockout logic |",
            "| `test_attack_core.py` | 34 | pure attack functions |",
            "| `test_common.py` | 31 | password + DB utilities |",
            "| `test_coverage_extra.py` | 45 | edge cases |",
            "| `test_db.py` | 5 | schema invariants |",
            "| `test_integration.py` | 1 | end-to-end run |",
            "| `test_make_coverage_badge.py` | 22 | badge generator |",
            "| `test_radar_anomaly.py` | 16 | Z-score detection |",
            "| `test_radar_pdf.py` | 7 | PDF builder |",
            "| `test_radar_period.py` | 17 | period comparison |",
            "| `test_smoke.py` | 6 | import cleanliness |",
            "| `test_telecom_attack_db.py` | 21 | DB layer |",
            "| `test_unit.py` | 19 | Luhn, haversine, generators |",
            "",
            "## Coverage",
            "",
            "```bash",
            "coverage erase",
            "coverage run --source=. -m pytest --run-slow -q",
            "coverage report",
            "```",
            "",
            "Current coverage: **98%** on core services.",
            "",
            "## CI",
            "",
            "Every push runs GitHub Actions on Python 3.11, 3.12, 3.13:",
            "",
            "1. Install dependencies from `requirements-ci.txt`",
            "2. Verify packages import cleanly",
            "3. Generate a minimal dataset",
            "4. Run fast tests",
            "5. Run slow tests",
            "",
            "## pre-commit hooks",
            "",
            "```bash",
            "pre-commit install",
            "pre-commit run --all-files",
            "```",
            "",
        ]
    ),
)


# ---------------------------------------------------------------
# docs/security.md
# ---------------------------------------------------------------
w(
    "docs/security.md",
    "\n".join(
        [
            "# Security Model",
            "",
            "## Threat Model",
            "",
            "Designed for **offline, single-host operation**.",
            "",
            "- The host is trusted.",
            "- Dashboards are accessed from the same machine (127.0.0.1).",
            "- No data ever leaves the host.",
            "",
            "## Guarantees",
            "",
            "### Zero external network calls",
            "",
            "Verified by static analysis:",
            "",
            "```bash",
            "python generate_evidence.py",
            "```",
            "",
            "### Streamlit telemetry disabled",
            "",
            "`.streamlit/config.toml`:",
            "",
            "```toml",
            "[server]",
            'address = "127.0.0.1"',
            "",
            "[browser]",
            "gatherUsageStats = false",
            "```",
            "",
            "### Loopback-only binding",
            "",
            "```bash",
            "netstat -ano | findstr :8501",
            "```",
            "",
            "Every address must be `127.0.0.1`. Red flags: `0.0.0.0:8501` or `[::]:8501`.",
            "",
            "### Password hashing",
            "",
            "Admin passwords use **scrypt**:",
            "",
            "- `n = 2^14`",
            "- `r = 8`",
            "- `p = 1`",
            "- `dklen = 32`",
            "",
            "Salt is 16 random bytes from `secrets.token_bytes()`.",
            "Comparison uses `hmac.compare_digest`.",
            "",
            "### Login rate-limiting",
            "",
            "5 failed attempts within 15 minutes triggers a lockout.",
            "Counter lives in `audit_log` (not `session_state`).",
            "",
            "### Backup integrity",
            "",
            "- WAL-aware snapshots via `sqlite3.Connection.backup()`",
            "- `PRAGMA quick_check` before restore",
            "- Path-traversal protection",
            "",
            "## Reporting a vulnerability",
            "",
            "Please **do not** open a public issue. Use GitHub Security Advisories.",
            "",
        ]
    ),
)


# ---------------------------------------------------------------
# docs/contributing.md
# ---------------------------------------------------------------
w(
    "docs/contributing.md",
    "\n".join(
        [
            "# Contributing",
            "",
            "## Development setup",
            "",
            "```bash",
            "git clone https://github.com/hosras/MNO-simulator.git",
            "cd MNO-simulator",
            "python -m venv .venv",
            ".venv\\Scripts\\activate",
            "pip install -r requirements.txt",
            "pip install pre-commit ruff",
            "pre-commit install",
            "```",
            "",
            "## Before you commit",
            "",
            "1. Run ruff:",
            "",
            "```bash",
            "ruff check .",
            "ruff format .",
            "```",
            "",
            "2. Run tests:",
            "",
            "```bash",
            "pytest --run-slow -q",
            "```",
            "",
            "3. Regenerate docs (if you touched code or README):",
            "",
            "```bash",
            "python generate_readme.py",
            "python generate_evidence.py",
            "```",
            "",
            "## Commit message convention",
            "",
            "Follow Conventional Commits:",
            "",
            "| Prefix | When to use |",
            "|---|---|",
            "| `feat:` | New feature |",
            "| `fix:` | Bug fix |",
            "| `docs:` | Documentation only |",
            "| `test:` | Tests |",
            "| `chore:` | Tooling, deps, config |",
            "| `refactor:` | No behavior change |",
            "| `ci:` | CI/CD changes |",
            "",
            "Example: `feat(simulator): add --random-seed CLI flag`",
            "",
            "## Pull request checklist",
            "",
            "- [ ] Tests pass locally",
            "- [ ] `ruff check .` is clean",
            "- [ ] New code has docstrings and tests",
            "- [ ] Documentation updated",
            "- [ ] Commits follow the convention",
            "",
            "## Style guide",
            "",
            "- Line length: 100 characters",
            "- Quotes: double quotes",
            "- Imports: sorted by ruff",
            "- Docstrings: Google-style",
            "",
        ]
    ),
)


# ---------------------------------------------------------------
# docs/api/index.md
# ---------------------------------------------------------------
w(
    "docs/api/index.md",
    "\n".join(
        [
            "# API Reference",
            "",
            "Autogenerated from source docstrings using mkdocstrings.",
            "",
            "## Modules",
            "",
            "| Module | Purpose |",
            "|---|---|",
            "| `telecom_net_sim` | CLI simulator |",
            "| `attack_core` / `telecom_attack` | Attack simulation |",
            "| `telecom_common` | Shared utilities |",
            "| `admin.services` / `radar.services` | Business logic |",
            "",
        ]
    ),
)


# ---------------------------------------------------------------
# docs/api/simulator.md
# ---------------------------------------------------------------
w(
    "docs/api/simulator.md",
    "\n".join(
        [
            "# Simulator API",
            "",
            "## telecom_net_sim",
            "",
            "::: telecom_net_sim.CellSite",
            "",
            "::: telecom_net_sim.CoreNode",
            "",
            "::: telecom_net_sim.Subscriber",
            "",
            "::: telecom_net_sim.parse_args",
            "",
            "::: telecom_net_sim.build_topology",
            "",
            "::: telecom_net_sim.build_subscribers",
            "",
            "::: telecom_net_sim.gen_cdrs",
            "",
            "::: telecom_net_sim.main",
            "",
        ]
    ),
)


# ---------------------------------------------------------------
# docs/api/attack.md
# ---------------------------------------------------------------
w(
    "docs/api/attack.md",
    "\n".join(
        [
            "# Attack Simulation API",
            "",
            "## Pure core - attack_core",
            "",
            "::: attack_core.pick_target",
            "",
            "::: attack_core.generate_scenarios",
            "",
            "::: attack_core.expand_events",
            "",
            "::: attack_core.attacks_to_alerts",
            "",
            "## DB layer - telecom_attack",
            "",
            "::: telecom_attack.init_attack_tables",
            "",
            "::: telecom_attack.generate_attack_scenarios",
            "",
            "::: telecom_attack.persist_attacks",
            "",
            "::: telecom_attack.inject_attack_alerts",
            "",
            "::: telecom_attack.run_attack_simulation",
            "",
        ]
    ),
)


# ---------------------------------------------------------------
# docs/api/common.md
# ---------------------------------------------------------------
w(
    "docs/api/common.md",
    "\n".join(
        [
            "# Common Utilities API",
            "",
            "## Database",
            "",
            "::: telecom_common.db_connect",
            "",
            "::: telecom_common.db_df",
            "",
            "::: telecom_common.db_exec",
            "",
            "::: telecom_common.db_one",
            "",
            "::: telecom_common.db_count",
            "",
            "::: telecom_common.db_chunked_in_update",
            "",
            "## Password",
            "",
            "::: telecom_common.has_password",
            "",
            "::: telecom_common.set_password",
            "",
            "::: telecom_common.verify_password",
            "",
            "## Identity generators",
            "",
            "::: telecom_common.luhn",
            "",
            "::: telecom_common.gen_imsi",
            "",
            "::: telecom_common.gen_msisdn",
            "",
            "::: telecom_common.gen_imei",
            "",
            "::: telecom_common.gen_key_id",
            "",
        ]
    ),
)


# ---------------------------------------------------------------
# docs/api/services.md
# ---------------------------------------------------------------
w(
    "docs/api/services.md",
    "\n".join(
        [
            "# Services API",
            "",
            "## Backup - admin.services.backup",
            "",
            "::: admin.services.backup.create_backup",
            "",
            "::: admin.services.backup.list_backups",
            "",
            "::: admin.services.backup.restore_backup",
            "",
            "## Audit - admin.services.audit",
            "",
            "::: admin.services.audit.init_audit",
            "",
            "::: admin.services.audit.log_audit",
            "",
            "## Anomaly detection - radar.services.anomaly",
            "",
            "::: radar.services.anomaly.detect_anomalies",
            "",
            "## Period comparison - radar.services.period",
            "",
            "::: radar.services.period.split_periods",
            "",
            "::: radar.services.period.period_stats",
            "",
            "::: radar.services.period.delta_pct",
            "",
            "## PDF reports - radar.services.pdf",
            "",
            "::: radar.services.pdf.build_pdf",
            "",
        ]
    ),
)


print()
print("DONE - 13 files created.")
print()
print("Next:")
print("  pip install -r requirements-docs.txt")
print("  mkdocs serve")
